/* GENERADO — NO EDITAR A MANO.
 * Vendorizado desde cms-estaciones:src/payload-types.ts en el ref 0190393.
 * Regenerar con: pnpm sync:types  (el pin vive en payload-types.lock.json).
 * Nota: se quita la augmentation `declare module 'payload'` del upstream
 *       (el front no instala el paquete payload; solo usa las interfaces).
 */
/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    noticias: Noticia;
    programas: Programa;
    podcasts: Podcast;
    categorias: Categoria;
    etiquetas: Etiqueta;
    especiales: Especiale;
    listas: Lista;
    'tipos-de-lista': TiposDeLista;
    eventos: Evento;
    transmisiones: Transmisione;
    publicidad: Publicidad;
    promociones: Promocione;
    autores: Autore;
    bitacora: Bitacora;
    canciones: Cancione;
    'estado-muestras': EstadoMuestra;
    avisos: Aviso;
    paginas: Pagina;
    estaciones: Estacione;
    auditoria: Auditoria;
    search: Search;
    redirects: Redirect;
    exports: Export;
    imports: Import;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    noticias: {
      colecciones: 'especiales';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    noticias: NoticiasSelect<false> | NoticiasSelect<true>;
    programas: ProgramasSelect<false> | ProgramasSelect<true>;
    podcasts: PodcastsSelect<false> | PodcastsSelect<true>;
    categorias: CategoriasSelect<false> | CategoriasSelect<true>;
    etiquetas: EtiquetasSelect<false> | EtiquetasSelect<true>;
    especiales: EspecialesSelect<false> | EspecialesSelect<true>;
    listas: ListasSelect<false> | ListasSelect<true>;
    'tipos-de-lista': TiposDeListaSelect<false> | TiposDeListaSelect<true>;
    eventos: EventosSelect<false> | EventosSelect<true>;
    transmisiones: TransmisionesSelect<false> | TransmisionesSelect<true>;
    publicidad: PublicidadSelect<false> | PublicidadSelect<true>;
    promociones: PromocionesSelect<false> | PromocionesSelect<true>;
    autores: AutoresSelect<false> | AutoresSelect<true>;
    bitacora: BitacoraSelect<false> | BitacoraSelect<true>;
    canciones: CancionesSelect<false> | CancionesSelect<true>;
    'estado-muestras': EstadoMuestrasSelect<false> | EstadoMuestrasSelect<true>;
    avisos: AvisosSelect<false> | AvisosSelect<true>;
    paginas: PaginasSelect<false> | PaginasSelect<true>;
    estaciones: EstacionesSelect<false> | EstacionesSelect<true>;
    auditoria: AuditoriaSelect<false> | AuditoriaSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      aplicarProgramacion: TaskAplicarProgramacion;
      limpiarBitacora: TaskLimpiarBitacora;
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'superadmin' | 'admin-estacion' | 'editor-estacion';
  estaciones?:
    | {
        estacion: number | Estacione;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estaciones".
 */
export interface Estacione {
  id: number;
  /**
   * Nombre interno, CON frecuencia (ej. "Beat 100.9"). Es el que se ve en el admin y en el selector de estación, así que la frecuencia ayuda a distinguirlas.
   */
  nombre: string;
  /**
   * Identificador corto y estable (beat, oye, sabrosita, stereocien). NO cambiarlo: de él cuelgan los datos migrados y las referencias externas.
   */
  codigo: string;
  /**
   * Nombre público de la marca, SIN frecuencia (ej. "BEAT"). Es el que sale en feeds RSS, news-sitemap y metadatos SEO.
   */
  nombrePublicacion: string;
  /**
   * Dominio del front, sin protocolo ni www (ej. "beatdigital.mx"). Con esto cada sitio resuelve host → estación. Indexado porque es una consulta por request.
   */
  dominio: string;
  /**
   * Color primario en hex (ej. "#EA262A"). Sirve para distinguir la estación en el admin y para el tema del front.
   */
  color?: string | null;
  /**
   * Ruta del logo en /public/branding/estaciones/. Es un archivo del repo, no un upload: es asset de marca, no contenido editorial.
   */
  logo?: string | null;
  /**
   * Variante para fondos oscuros, si existe. Beat y Oye son monocromáticos y tienen las dos; Stereo Cien y Sabrosita todavía no.
   */
  logoReversa?: string | null;
  /**
   * Mount de Triton Digital (ej. "XHSONFM"). Es lo único que necesita el SDK de Triton en el front para reproducir el aire.
   */
  tritonMount?: string | null;
  /**
   * Aclaraciones sobre qué transmite este mount, si no es obvio. Ver el caso de Stereo Cien.
   */
  notaStream?: string | null;
  /**
   * Enciéndelo SOLO mientras corre una campaña de preroll vendida, y apágalo al terminar: mientras esté prendido el player le pide anuncio a Google Ad Manager antes de abrir el aire, y si no hay campaña eso solo lo hace arrancar más lento.
   */
  preroll?: boolean | null;
  /**
   * Solo estas categorías se guardan en la bitácora al aire. Si está vacía, no se guarda nada de esta estación (falla cerrado a propósito). El endpoint de ingesta responde qué categoría rechazó, para ir descubriendo la lista.
   */
  categoriasMusicales?:
    | {
        categoria: string;
        id?: string | null;
      }[]
    | null;
  facebook?: string | null;
  instagram?: string | null;
  x?: string | null;
  youtube?: string | null;
  tiktok?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * ID de origen en WordPress (solo migración). No editar a mano.
   */
  wpId?: number | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias".
 */
export interface Noticia {
  id: number;
  estacion?: (number | null) | Estacione;
  titulo: string;
  resumen?: string | null;
  /**
   * Texto libre de respaldo para migraciones o colaboraciones externas.
   */
  autor?: string | null;
  /**
   * Quién participó en la nota, del catálogo de fichas.
   */
  autores?: (number | Autore)[] | null;
  /**
   * Tratamiento EDITORIAL de la nota (independiente del formato). No agrega campos.
   */
  tipo?: ('estandar' | 'breaking-news' | 'reportaje-especial') | null;
  /**
   * Plantilla del frontend. Video/Galería/Audio muestran sus campos y pueden ir sin cuerpo.
   */
  formato?: ('estandar' | 'video' | 'galeria' | 'audio') | null;
  video?: {
    plataforma?: ('youtube' | 'vimeo' | 'archivo') | null;
    /**
     * URL pública en YouTube o Vimeo. Se guarda solo la URL.
     */
    url?: string | null;
    /**
     * Se sube a Media como cualquier archivo (Sharp solo procesa imágenes; el video se guarda tal cual). Un mp4 pesa mucho más que una foto: si el video ya está en YouTube o Vimeo, conviene enlazarlo en vez de subirlo.
     */
    archivo?: (number | null) | Media;
    /**
     * Se muestra en la lista de la colección (ej. 4:12).
     */
    duracion?: string | null;
    /**
     * El front no la puede adivinar antes de cargar el video, y de eso depende cómo reserva el espacio.
     */
    orientacion?: ('horizontal' | 'vertical') | null;
  };
  /**
   * Arrastra para reordenar. Se muestran en el orden de la lista.
   */
  galeria?:
    | {
        imagen: number | Media;
        pie?: string | null;
        id?: string | null;
      }[]
    | null;
  audio?: {
    fuente?: ('embed' | 'archivo') | null;
    /**
     * Pega la URL del embed, o el código <iframe> completo que da la plataforma: se limpia solo. Aceptadas: OmnyStudio, SoundCloud, Mixcloud, Spotify, Apple Podcasts, Amazon Music, Deezer, Spreaker, Audioboom, Podbean, Buzzsprout, Simplecast, Libsyn, Megaphone, iono.fm, iVoox, Anchor. (Para un video de YouTube usa el formato Video.)
     */
    embedUrl?: string | null;
    archivo?: (number | null) | Media;
  };
  /**
   * La imagen de la nota: portada, tarjetas, RSS y lo que se ve al compartirla. Es obligatoria para publicar.
   */
  imagen: number | Media;
  /**
   * Cuerpo de la nota. Opcional en formatos Video/Galería/Audio.
   */
  contenido?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Ordena TODOS los listados públicos. Se llena sola con la hora de creación; cámbiala solo si la nota es de otro día.
   */
  fecha: string;
  fechaManual?: boolean | null;
  categorias?: (number | Categoria)[] | null;
  etiquetas?: (number | Etiqueta)[] | null;
  /**
   * Agrupa esta nota bajo una cobertura especial. Es el camino PASIVO: la nota entra al montón cronológico de esa cobertura, sin orden. Si la nota es una pieza curada (una cápsula), no se usa esto: se agrega desde la lista, que es donde vive el orden.
   */
  especial?: (number | null) | Especiale;
  /**
   * Se llena solo. Para agregarla a una lista, se hace desde ella.
   */
  colecciones?: {
    docs?: (number | Especiale)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Se publicará automáticamente en esta fecha/hora. Si pones una fecha futura, la nota se guarda como Despublicada y sale sola al llegar el momento. Para publicarla de inmediato, cambia el estado a Publicada: la programación se cancela.
   */
  publicarEn?: string | null;
  /**
   * Se despublicará automáticamente en esta fecha/hora.
   */
  despublicarEn?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Usar solo si este contenido debe apuntar a otra URL canónica.
     */
    canonicalUrl?: string | null;
    /**
     * Excluye del sitemap/RSS y permite que el frontend agregue noindex.
     */
    noIndex?: boolean | null;
    /**
     * Solo aplica a noticias.
     */
    incluirEnNewsSitemap?: boolean | null;
  };
  /**
   * URL publica. Si queda vacio, se genera desde el titulo.
   */
  slug?: string | null;
  /**
   * Despublicar oculta la nota del sitio sin borrarla.
   */
  estado?: ('publicada' | 'despublicada') | null;
  /**
   * Una pieza de lista conserva su URL, su sitemap y el buscador; lo que no hace es distribuirse como noticia.
   */
  distribucion?: ('noticia' | 'pieza') | null;
  /**
   * Excepción de COLOCACIÓN para una nota normal: se guarda y aparece en su sección, pero nunca en el home. Para las cápsulas no hace falta tocarlo — su `distribucion` ya las saca. El front filtra con where[excluirDelHome][not_equals]=true.
   */
  excluirDelHome?: boolean | null;
  /**
   * Mantiene la noticia arriba en los listados hasta que se desfije.
   */
  fijada?: boolean | null;
  /**
   * Opcional. Se desfija sola en esta fecha; vacío = fijada hasta apagar el switch.
   */
  fijadaHasta?: string | null;
  /**
   * ID de origen en WordPress (solo migración). No editar a mano.
   */
  wpId?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "autores".
 */
export interface Autore {
  id: number;
  estacion?: (number | null) | Estacione;
  nombre: string;
  /**
   * URL publica/perfil del autor. Si queda vacio, se genera desde el nombre.
   */
  slug?: string | null;
  tipos: ('autor' | 'redactor' | 'reportero' | 'locutor')[];
  /**
   * Ej. Conductora, Reportero de politica, Editor digital.
   */
  cargo?: string | null;
  bio?: string | null;
  foto?: (number | null) | Media;
  emailPublico?: string | null;
  x?: string | null;
  instagram?: string | null;
  /**
   * ID de origen en WordPress (solo migración). No editar a mano.
   */
  wpId?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias".
 */
export interface Categoria {
  id: number;
  estacion?: (number | null) | Estacione;
  nombre: string;
  /**
   * URL pública. Si queda vacío, se genera desde el nombre.
   */
  slug?: string | null;
  descripcion?: string | null;
  /**
   * ID de origen en WordPress (solo migración). No editar a mano.
   */
  wpId?: number | null;
  parent?: (number | null) | Categoria;
  breadcrumbs?:
    | {
        doc?: (number | null) | Categoria;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "etiquetas".
 */
export interface Etiqueta {
  id: number;
  estacion?: (number | null) | Estacione;
  nombre: string;
  /**
   * URL pública. Si queda vacío, se genera desde el nombre.
   */
  slug?: string | null;
  descripcion?: string | null;
  /**
   * ID de origen en WordPress (solo migración). No editar a mano.
   */
  wpId?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Agrupa contenido bajo una cobertura o un tema: el de la semana, un festival, una serie. Para una lista de canciones (top ten, lanzamientos) usa «Listas».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "especiales".
 */
export interface Especiale {
  id: number;
  estacion?: (number | null) | Estacione;
  titulo: string;
  descripcion?: string | null;
  /**
   * Opcional. Si este especial es de un programa en particular, elígelo aquí.
   */
  programa?: (number | null) | Programa;
  /**
   * La sección del sitio de la que es entrega (ej. "El Fenómeno Residente"). Vacío = lista suelta, que vive por su cuenta.
   */
  serie?: (number | null) | Categoria;
  /**
   * Cómo la nombra el sitio arriba del título. Cada serie usa la suya ("Tema de la semana", "Entrega", "Cobertura"), y por eso es un campo y no una palabra fija del CMS.
   */
  etiquetaPublica?: string | null;
  /**
   * Desde cuándo está al aire.
   */
  inicio?: string | null;
  fin?: string | null;
  /**
   * La imagen con la que esto aparece LISTADO en otras páginas (tarjetas, módulos). El encabezado de su propia página se arma abajo, en «Cabecera».
   */
  portada?: (number | null) | Media;
  /**
   * Cómo se ve el encabezado de la página. Todo es opcional: sin nada, el sitio usa su diseño de siempre.
   */
  cabecera?: {
    fondo?: ('ninguno' | 'imagen' | 'color' | 'degradado') | null;
    /**
     * Se recorta según la pantalla, así que lo importante debe estar al centro. El texto va encima: mejor una imagen con zonas tranquilas que una llena de detalle.
     */
    imagen?: (number | null) | Media;
    color?: string | null;
    colorFin?: string | null;
    /**
     * Se guarda como el ángulo de CSS, tal cual lo usa el degradado.
     */
    direccion?: ('180deg' | '0deg' | '90deg' | '135deg') | null;
    /**
     * El logotipo propio de esto, si lo tiene. Se muestra en la cabecera en vez del título escrito. Conviene PNG o SVG con fondo transparente.
     */
    logo?: (number | null) | Media;
  };
  /**
   * Opcional. La lista asociada a este especial (un top ten, la selección del tema). Sale de «Listas».
   */
  lista?: (number | null) | Lista;
  /**
   * Lo que compone la lista, en el orden en que se muestra: arrastra para reordenar. Admite tipos distintos —una nota de video, un podcast, una transmisión— porque justo eso es lo que la hace una lista y no una categoría.
   */
  piezas?:
    | (
        | {
            relationTo: 'noticias';
            value: number | Noticia;
          }
        | {
            relationTo: 'podcasts';
            value: number | Podcast;
          }
        | {
            relationTo: 'transmisiones';
            value: number | Transmisione;
          }
        | {
            relationTo: 'listas';
            value: number | Lista;
          }
      )[]
    | null;
  /**
   * La que encabeza la página. En el Fenómeno Residente es el especial del sábado; en una cobertura, la nota principal.
   */
  piezaDestacada?:
    | ({
        relationTo: 'noticias';
        value: number | Noticia;
      } | null)
    | ({
        relationTo: 'podcasts';
        value: number | Podcast;
      } | null)
    | ({
        relationTo: 'transmisiones';
        value: number | Transmisione;
      } | null)
    | ({
        relationTo: 'listas';
        value: number | Lista;
      } | null);
  /**
   * Va como grupo de campos y no como colección propia: hoy hay un solo caso real. Cuando el segundo llegue de verdad (el mapa promete espacios patrocinables en eventos y en Beat MDMA), se extrae a su colección y esto se migra.
   */
  patrocinador?: {
    nombre?: string | null;
    logo?: (number | null) | Media;
    enlace?: string | null;
  };
  /**
   * URL pública. Si queda vacío, se genera desde el título.
   */
  slug?: string | null;
  estado?: ('activo' | 'archivado') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programas".
 */
export interface Programa {
  id: number;
  estacion?: (number | null) | Estacione;
  nombre: string;
  /**
   * Una línea para la celda de la parrilla y las tarjetas. Si se deja vacía, el front tendrá que recortar la descripción larga.
   */
  descripcionCorta?: string | null;
  descripcion?: string | null;
  /**
   * Fichas de la colección Autores con el tipo "Locutor".
   */
  locutores?: (number | Autore)[] | null;
  /**
   * Portada del programa: parrilla, tarjetas y su página.
   */
  imagen?: (number | null) | Media;
  /**
   * Un bloque por cada rango que se repite igual. "Lunes a viernes 06:00–10:00" es UN bloque con los cinco días marcados; si el sábado va a otra hora, ese es un segundo bloque.
   */
  horarios?:
    | {
        /**
         * Los días en que este bloque se transmite a la misma hora.
         */
        dias: ('lun' | 'mar' | 'mie' | 'jue' | 'vie' | 'sab' | 'dom')[];
        horaInicio: string;
        horaFin: string;
        /**
         * Las repeticiones se marcan para que el front pueda distinguirlas en la parrilla y no anunciar como "en vivo" algo grabado.
         */
        tipo?: ('vivo' | 'repeticion') | null;
        id?: string | null;
      }[]
    | null;
  whatsapp?: string | null;
  telefono?: string | null;
  hashtag?: string | null;
  /**
   * URL pública (/programas/...). Si queda vacío, se genera del nombre.
   */
  slug?: string | null;
  /**
   * Archivar lo saca de la parrilla sin borrar su página ni sus episodios.
   */
  estado?: ('activo' | 'archivado') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Las listas de canciones del sitio. Cada edición es su propio documento: para la de esta semana, duplica la anterior y cámbiale las canciones —la fecha y la URL se ponen solas. Qué listas existen se define en «Tipos de lista».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listas".
 */
export interface Lista {
  id: number;
  estacion?: (number | null) | Estacione;
  titulo: string;
  /**
   * Qué lista es. Se elige de las que tenga definidas esta estación (colección «Tipos de lista»). Es parte de la URL.
   */
  tipo: number | TiposDeLista;
  fecha: string;
  /**
   * Opcional. Si esta lista es de un programa en particular, elígelo aquí.
   */
  programa?: (number | null) | Programa;
  /**
   * Opcional. Un par de líneas para la página de la lista.
   */
  descripcion?: string | null;
  /**
   * El orden de la lista es el orden de aquí: arrastra para reordenar. Las canciones salen del catálogo, que se llena solo con lo que suena al aire.
   */
  canciones?:
    | {
        cancion: number | Cancione;
        /**
         * Opcional. La viñeta que acompaña a la canción en el sitio: por qué está aquí, qué contar de ella.
         */
        comentario?: string | null;
        /**
         * Los escribe el sitio público; aquí solo se ven.
         */
        votos?: number | null;
        id?: string | null;
      }[]
    | null;
  playlistSpotify?: string | null;
  playlistAppleMusic?: string | null;
  /**
   * La imagen de la lista: con la que aparece listada en otras páginas y con la que se comparte.
   */
  portada?: (number | null) | Media;
  /**
   * URL pública. Se arma sola con el tipo y la fecha; cambia la fecha y cambia esto.
   */
  slug?: string | null;
  /**
   * Nace despublicada: publícala cuando la lista esté completa.
   */
  estado?: ('publicada' | 'despublicada') | null;
  /**
   * Mientras esté encendida, el sitio puede sumar votos a las canciones de esta lista. Apagarla cierra la votación sin borrar los conteos.
   */
  votacionAbierta?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Las listas que existen en el sitio de esta estación (Top Ten, Bonus Beat, Lanzamientos). Cada estación define las suyas; al capturar una lista se elige de aquí.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipos-de-lista".
 */
export interface TiposDeLista {
  id: number;
  estacion?: (number | null) | Estacione;
  /**
   * Como lo llama la estación: «Top Ten», «Bonus Beat», «Hot Parade».
   */
  nombre: string;
  /**
   * Opcional. Qué es esta lista, para la página de su archivo histórico en el sitio.
   */
  descripcion?: string | null;
  /**
   * Con esto el sitio pide esta lista, y con esto empieza la URL de cada edición. Si queda vacío se genera del nombre. Cambiarlo después le cambia la URL a las ediciones.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Se llena sola con lo que suena al aire en Dalet. Enriquécela con portada, reproductor y enlaces a plataformas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "canciones".
 */
export interface Cancione {
  id: number;
  estacion?: (number | null) | Estacione;
  titulo: string;
  artista?: string | null;
  /**
   * La rellena la ingesta con lo que manda Dalet, la primera vez que la canción suena. Es la que se muestra en la playlist de una lista.
   */
  duracion?: string | null;
  /**
   * Opcional. Dalet no la manda; se sube a mano.
   */
  portada?: (number | null) | Media;
  /**
   * Pega la URL del video o del audio, o el código <iframe> completo que da la plataforma: se limpia solo. Aceptadas: OmnyStudio, SoundCloud, Mixcloud, Spotify, Apple Podcasts, Amazon Music, Deezer, Spreaker, Audioboom, Podbean, Buzzsprout, Simplecast, Libsyn, Megaphone, iono.fm, iVoox, Anchor, YouTube, Vimeo.
   */
  embedUrl?: string | null;
  /**
   * Opcional. El mp3 que se reproduce en el sitio. Solo material del que la estación tenga derechos de reproducción a demanda: no es lo mismo que emitirlo al aire.
   */
  audio?: (number | null) | Media;
  spotify?: string | null;
  appleMusic?: string | null;
  youtube?: string | null;
  deezer?: string | null;
  /**
   * Quién creó la ficha. «Dalet» = la creó sola la ingesta la primera vez que la canción sonó al aire.
   */
  origen?: ('dalet' | 'manual') | null;
  /**
   * Id de biblioteca de Dalet. Lo escribe la ingesta y no se edita: es la llave que evita duplicados y permite cruzar con lo que salió Al Aire.
   */
  selector?: string | null;
  /**
   * Como la reporta Dalet (ej. MUSICA-HOUSE). Informativa.
   */
  categoriaPlayout?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcasts".
 */
export interface Podcast {
  id: number;
  estacion?: (number | null) | Estacione;
  titulo: string;
  resumen?: string | null;
  /**
   * Texto libre de respaldo para migraciones o colaboraciones externas.
   */
  autor?: string | null;
  /**
   * Quién participó en el audio, del catálogo de fichas.
   */
  autores?: (number | Autore)[] | null;
  /**
   * Portada del episodio
   */
  imagen?: (number | null) | Media;
  programa: number | Programa;
  temporada?: number | null;
  episodio?: number | null;
  fuente: 'embed' | 'archivo';
  /**
   * Pega la URL del embed, o el código <iframe> completo que da la plataforma: se limpia solo. Aceptadas: OmnyStudio, SoundCloud, Mixcloud, Spotify, Apple Podcasts, Amazon Music, Deezer, Spreaker, Audioboom, Podbean, Buzzsprout, Simplecast, Libsyn, Megaphone, iono.fm, iVoox, Anchor.
   */
  embedUrl?: string | null;
  audio?: (number | null) | Media;
  /**
   * Opcional. Si el episodio también está filmado, aquí va: enlace de YouTube o Vimeo, o un archivo mp4 subido a Media.
   */
  video?: {
    fuente?: ('ninguno' | 'youtube' | 'vimeo' | 'archivo') | null;
    /**
     * Pega el enlace del video, o el código <iframe> completo que da la plataforma: se limpia solo. Aceptadas: YouTube, Vimeo.
     */
    url?: string | null;
    /**
     * Se sube a Media como cualquier archivo (Sharp solo procesa imágenes, el video se guarda tal cual). Un mp4 pesa mucho más que una foto: si el video ya está en YouTube o Vimeo, conviene enlazarlo en vez de subirlo.
     */
    archivo?: (number | null) | Media;
  };
  /**
   * Ordena el listado y el RSS de podcasts. Se llena sola con la hora de creación.
   */
  fecha: string;
  categorias?: (number | Categoria)[] | null;
  etiquetas?: (number | Etiqueta)[] | null;
  /**
   * Se publicará automáticamente en esta fecha/hora. Si pones una fecha futura, la nota se guarda como Despublicada y sale sola al llegar el momento. Para publicarla de inmediato, cambia el estado a Publicada: la programación se cancela.
   */
  publicarEn?: string | null;
  /**
   * Se despublicará automáticamente en esta fecha/hora.
   */
  despublicarEn?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Usar solo si este contenido debe apuntar a otra URL canónica.
     */
    canonicalUrl?: string | null;
    /**
     * Excluye del sitemap/RSS y permite que el frontend agregue noindex.
     */
    noIndex?: boolean | null;
    /**
     * Solo aplica a noticias.
     */
    incluirEnNewsSitemap?: boolean | null;
  };
  /**
   * URL publica. Si queda vacio, se genera desde el titulo.
   */
  slug?: string | null;
  /**
   * Despublicar oculta el episodio del sitio sin borrarlo.
   */
  estado?: ('publicada' | 'despublicada') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transmisiones".
 */
export interface Transmisione {
  id: number;
  estacion?: (number | null) | Estacione;
  titulo: string;
  descripcion?: string | null;
  /**
   * Configuración opcional de transmisión en vivo. El toggle "activo" controla si se muestra en el frontend; el embed puede quedar guardado aunque esté apagado.
   */
  videoEnVivo?: {
    activo?: boolean | null;
    fuente?: ('iframe' | 'numero-evento') | null;
    /**
     * URL a insertar en el iframe del player en vivo.
     */
    url?: string | null;
    /**
     * ID/número de evento de la plataforma de streaming.
     */
    numeroEvento?: string | null;
  };
  fecha?: string | null;
  /**
   * Liga esta transmision a un Especial si aplica.
   */
  especial?: (number | null) | Especiale;
  updatedAt: string;
  createdAt: string;
}
/**
 * Lo que la estación organiza, cubre o donde tiene presencia. Las fechas llevan hora, y el evento dice por sí mismo si lleva RSVP o venta de boletos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventos".
 */
export interface Evento {
  id: number;
  estacion?: (number | null) | Estacione;
  titulo: string;
  /**
   * Con esto el sitio arma sus filtros de la agenda.
   */
  tipo: 'propio' | 'cobertura' | 'festival';
  /**
   * Día y hora. Es lo que ordena la agenda.
   */
  inicio: string;
  /**
   * Opcional. Solo para lo que dura varios días o toda una tarde.
   */
  fin?: string | null;
  /**
   * Un párrafo: qué es, quién toca, por qué importa.
   */
  descripcion?: string | null;
  lugar?: string | null;
  ciudad?: string | null;
  accion?: ('ninguna' | 'rsvp' | 'boletos') | null;
  /**
   * La liga del registro o de la venta. Puede ser de un tercero.
   */
  enlace?: string | null;
  /**
   * La imagen con la que el evento aparece en la agenda y al compartirlo.
   */
  portada?: (number | null) | Media;
  /**
   * URL pública. Si queda vacío, se genera del título.
   */
  slug?: string | null;
  /**
   * Despublicar lo saca de la agenda sin borrarlo.
   */
  estado?: ('publicada' | 'despublicada') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Los banners del sitio: portada y banner nativo. Cada uno con su anunciante, su vigencia y su enlace. Fuera de vigencia deja de mostrarse solo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publicidad".
 */
export interface Publicidad {
  id: number;
  estacion?: (number | null) | Estacione;
  /**
   * Para identificarla aquí dentro. No se muestra en el sitio.
   */
  titulo: string;
  /**
   * De quién es la campaña. Es lo que agrupa los números al reportar.
   */
  anunciante: string;
  /**
   * Cada sitio ya sabe dónde va cada tipo.
   */
  tipo: 'portada' | 'nativo';
  /**
   * Antes de esta fecha el sitio no lo muestra.
   */
  inicio: string;
  /**
   * Vacío = sigue corriendo hasta que la pauses.
   */
  fin?: string | null;
  /**
   * La creatividad como la manda el anunciante.
   */
  imagen: number | Media;
  /**
   * Opcional. La versión vertical o cuadrada. Si se deja vacía, el sitio usa la de arriba.
   */
  imagenMovil?: (number | null) | Media;
  /**
   * La liga del anunciante. Puede ser externa o una página del propio sitio.
   */
  enlace: string;
  /**
   * Opcional. Cuando hay varias campañas corriendo al mismo tiempo en el mismo lugar, el sitio empieza por el número más bajo.
   */
  orden?: number | null;
  /**
   * Despublicarlo lo saca del sitio sin borrarlo ni perder sus números.
   */
  estado?: ('publicada' | 'despublicada') | null;
  impresiones?: number | null;
  clics?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Los concursos y promociones de la estación. Se puede participar con un formulario de aquí, con un concurso de otro sitio embebido, o fuera de línea (WhatsApp, cabina, redes).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promociones".
 */
export interface Promocione {
  id: number;
  estacion?: (number | null) | Estacione;
  titulo: string;
  /**
   * Qué se gana, en una línea. Es lo que va en la tarjeta del listado.
   */
  premio?: string | null;
  /**
   * Día y hora en que abre la participación.
   */
  inicio: string;
  /**
   * Cuándo cierra. Vacío = sin fecha de término.
   */
  fin?: string | null;
  /**
   * De qué va el concurso y sus bases: quién puede participar, cómo se elige al ganador, qué incluye el premio.
   */
  descripcion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Define qué muestra el sitio: un formulario, un concurso de otro lado, o solo las instrucciones.
   */
  participacion: 'formulario' | 'externo' | 'fuera-de-linea';
  /**
   * Se arma en «Formularios». Lo que contesten los oyentes aparece en «Respuestas de formularios», que solo ven los admin.
   */
  formulario?: (number | null) | Form;
  /**
   * Solo la dirección, no el código del iframe. El sitio lo arma con ella.
   */
  urlExterna?: string | null;
  /**
   * Lo que tiene que hacer el oyente. Ej.: «Manda un WhatsApp al 55 1234 5678 con la palabra BEAT».
   */
  instrucciones?: string | null;
  /**
   * Se llena cuando el concurso cierra. Vacío, el sitio no muestra nada — no hace falta despublicar la promoción para que no salga.
   */
  ganadores?: string | null;
  /**
   * La imagen con la que la promoción aparece en el listado y al compartirla.
   */
  portada?: (number | null) | Media;
  /**
   * URL pública. Si queda vacío, se genera del título.
   */
  slug?: string | null;
  /**
   * Despublicar la saca del sitio sin borrarla. Un concurso ya cerrado puede seguir publicado para mostrar a los ganadores.
   */
  estado?: ('publicada' | 'despublicada') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * La escribe Dalet automáticamente. Se conservan los últimos 7 días.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bitacora".
 */
export interface Bitacora {
  id: number;
  estacion?: (number | null) | Estacione;
  sonoEn: string;
  titulo: string;
  artista?: string | null;
  /**
   * La ficha del catálogo. El título y el artista se guardan TAMBIÉN aquí, planos, a propósito: si la ficha se edita o se borra, la bitácora sigue diciendo qué sonó de verdad ese día.
   */
  cancion?: (number | null) | Cancione;
  /**
   * Id de biblioteca de Dalet.
   */
  selector?: string | null;
  categoriaPlayout?: string | null;
  /**
   * Como la manda Dalet (HH:MM:SS). Texto, no se interpreta.
   */
  duracion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estado-muestras".
 */
export interface EstadoMuestra {
  id: number;
  momento: string;
  /**
   * Mapa id de sonda → nivel (ok, advertencia, falla, desconocido).
   */
  niveles?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Se muestran en /admin/estado y como banner en todo el panel hasta que se marcan como resueltos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avisos".
 */
export interface Aviso {
  id: number;
  /**
   * Corto y en lenguaje de redacción: "Las imágenes tardan en subir".
   */
  titulo: string;
  /**
   * Decide el color del banner.
   */
  severidad: 'informativo' | 'degradado' | 'interrupcion';
  /**
   * Al marcarlo "Resuelto" desaparece el banner.
   */
  estado: 'investigando' | 'identificado' | 'monitoreando' | 'resuelto';
  /**
   * Qué pasa, a quién afecta y qué hacer mientras tanto. Se lee completo en /admin/estado.
   */
  mensaje: string;
  componentes?: ('editor' | 'imagenes' | 'programacion' | 'busqueda' | 'bitacora' | 'sitio' | 'correo')[] | null;
  /**
   * Déjalo VACÍO si afecta a todas (por ejemplo, algo de infraestructura). Si eliges una o varias, el banner solo le sale a quien trabaja en ellas.
   */
  estaciones?: (number | Estacione)[] | null;
  inicio: string;
  resueltoEn?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Las páginas de texto fijo del sitio: aviso de privacidad, términos y condiciones, Alexa. Cada estación tiene las suyas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas".
 */
export interface Pagina {
  id: number;
  estacion?: (number | null) | Estacione;
  titulo: string;
  /**
   * El texto completo de la página. Acepta títulos, listas y enlaces.
   */
  contenido: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * URL pública (ej. aviso-de-privacidad). Si queda vacío se genera del título. Cambiarlo rompe los enlaces que ya apuntan aquí.
   */
  slug?: string | null;
  /**
   * Despublicar la saca del sitio sin borrarla.
   */
  estado?: ('publicada' | 'despublicada') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Registro automático de altas, cambios y borrados. Solo lectura: lo escribe el sistema.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auditoria".
 */
export interface Auditoria {
  id: number;
  coleccion: string;
  documentoId: string;
  documentoTitulo?: string | null;
  accion: 'crear' | 'actualizar' | 'borrar';
  /**
   * "Sistema" son cambios automáticos, como la publicación programada.
   */
  origen: 'panel' | 'sistema';
  usuario?: (number | null) | User;
  usuarioCorreo?: string | null;
  usuarioRol?: string | null;
  /**
   * Código de la estación del documento. Vacío si el cambio no es de una.
   */
  estacion?: string | null;
  /**
   * Lista corta para escanear el listado; el detalle va en "Cambios".
   */
  campos?: string | null;
  /**
   * Antes/después de cada campo, resumido. Los valores largos (contenido, imágenes) solo se marcan como cambiados.
   */
  cambios?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'noticias';
        value: number | Noticia;
      }
    | {
        relationTo: 'podcasts';
        value: number | Podcast;
      };
  estacion?: (number | null) | Estacione;
  categorias?: (number | Categoria)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'noticias';
          value: number | Noticia;
        } | null)
      | ({
          relationTo: 'podcasts';
          value: number | Podcast;
        } | null);
    url?: string | null;
  };
  type: '301' | '302';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: number;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  submissionUploads?:
    | {
        field: string;
        value: {
          relationTo: 'media';
          value: number | Media;
        }[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          'inline' | 'aplicarProgramacion' | 'limpiarBitacora' | 'createCollectionExport' | 'createCollectionImport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    ('inline' | 'aplicarProgramacion' | 'limpiarBitacora' | 'createCollectionExport' | 'createCollectionImport') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'noticias';
        value: number | Noticia;
      } | null)
    | ({
        relationTo: 'programas';
        value: number | Programa;
      } | null)
    | ({
        relationTo: 'podcasts';
        value: number | Podcast;
      } | null)
    | ({
        relationTo: 'categorias';
        value: number | Categoria;
      } | null)
    | ({
        relationTo: 'etiquetas';
        value: number | Etiqueta;
      } | null)
    | ({
        relationTo: 'especiales';
        value: number | Especiale;
      } | null)
    | ({
        relationTo: 'listas';
        value: number | Lista;
      } | null)
    | ({
        relationTo: 'tipos-de-lista';
        value: number | TiposDeLista;
      } | null)
    | ({
        relationTo: 'eventos';
        value: number | Evento;
      } | null)
    | ({
        relationTo: 'transmisiones';
        value: number | Transmisione;
      } | null)
    | ({
        relationTo: 'publicidad';
        value: number | Publicidad;
      } | null)
    | ({
        relationTo: 'promociones';
        value: number | Promocione;
      } | null)
    | ({
        relationTo: 'autores';
        value: number | Autore;
      } | null)
    | ({
        relationTo: 'bitacora';
        value: number | Bitacora;
      } | null)
    | ({
        relationTo: 'canciones';
        value: number | Cancione;
      } | null)
    | ({
        relationTo: 'estado-muestras';
        value: number | EstadoMuestra;
      } | null)
    | ({
        relationTo: 'avisos';
        value: number | Aviso;
      } | null)
    | ({
        relationTo: 'paginas';
        value: number | Pagina;
      } | null)
    | ({
        relationTo: 'estaciones';
        value: number | Estacione;
      } | null)
    | ({
        relationTo: 'auditoria';
        value: number | Auditoria;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  estaciones?:
    | T
    | {
        estacion?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  wpId?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias_select".
 */
export interface NoticiasSelect<T extends boolean = true> {
  estacion?: T;
  titulo?: T;
  resumen?: T;
  autor?: T;
  autores?: T;
  tipo?: T;
  formato?: T;
  video?:
    | T
    | {
        plataforma?: T;
        url?: T;
        archivo?: T;
        duracion?: T;
        orientacion?: T;
      };
  galeria?:
    | T
    | {
        imagen?: T;
        pie?: T;
        id?: T;
      };
  audio?:
    | T
    | {
        fuente?: T;
        embedUrl?: T;
        archivo?: T;
      };
  imagen?: T;
  contenido?: T;
  fecha?: T;
  fechaManual?: T;
  categorias?: T;
  etiquetas?: T;
  especial?: T;
  colecciones?: T;
  publicarEn?: T;
  despublicarEn?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalUrl?: T;
        noIndex?: T;
        incluirEnNewsSitemap?: T;
      };
  slug?: T;
  estado?: T;
  distribucion?: T;
  excluirDelHome?: T;
  fijada?: T;
  fijadaHasta?: T;
  wpId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programas_select".
 */
export interface ProgramasSelect<T extends boolean = true> {
  estacion?: T;
  nombre?: T;
  descripcionCorta?: T;
  descripcion?: T;
  locutores?: T;
  imagen?: T;
  horarios?:
    | T
    | {
        dias?: T;
        horaInicio?: T;
        horaFin?: T;
        tipo?: T;
        id?: T;
      };
  whatsapp?: T;
  telefono?: T;
  hashtag?: T;
  slug?: T;
  estado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcasts_select".
 */
export interface PodcastsSelect<T extends boolean = true> {
  estacion?: T;
  titulo?: T;
  resumen?: T;
  autor?: T;
  autores?: T;
  imagen?: T;
  programa?: T;
  temporada?: T;
  episodio?: T;
  fuente?: T;
  embedUrl?: T;
  audio?: T;
  video?:
    | T
    | {
        fuente?: T;
        url?: T;
        archivo?: T;
      };
  fecha?: T;
  categorias?: T;
  etiquetas?: T;
  publicarEn?: T;
  despublicarEn?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalUrl?: T;
        noIndex?: T;
        incluirEnNewsSitemap?: T;
      };
  slug?: T;
  estado?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias_select".
 */
export interface CategoriasSelect<T extends boolean = true> {
  estacion?: T;
  nombre?: T;
  slug?: T;
  descripcion?: T;
  wpId?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "etiquetas_select".
 */
export interface EtiquetasSelect<T extends boolean = true> {
  estacion?: T;
  nombre?: T;
  slug?: T;
  descripcion?: T;
  wpId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "especiales_select".
 */
export interface EspecialesSelect<T extends boolean = true> {
  estacion?: T;
  titulo?: T;
  descripcion?: T;
  programa?: T;
  serie?: T;
  etiquetaPublica?: T;
  inicio?: T;
  fin?: T;
  portada?: T;
  cabecera?:
    | T
    | {
        fondo?: T;
        imagen?: T;
        color?: T;
        colorFin?: T;
        direccion?: T;
        logo?: T;
      };
  lista?: T;
  piezas?: T;
  piezaDestacada?: T;
  patrocinador?:
    | T
    | {
        nombre?: T;
        logo?: T;
        enlace?: T;
      };
  slug?: T;
  estado?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listas_select".
 */
export interface ListasSelect<T extends boolean = true> {
  estacion?: T;
  titulo?: T;
  tipo?: T;
  fecha?: T;
  programa?: T;
  descripcion?: T;
  canciones?:
    | T
    | {
        cancion?: T;
        comentario?: T;
        votos?: T;
        id?: T;
      };
  playlistSpotify?: T;
  playlistAppleMusic?: T;
  portada?: T;
  slug?: T;
  estado?: T;
  votacionAbierta?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipos-de-lista_select".
 */
export interface TiposDeListaSelect<T extends boolean = true> {
  estacion?: T;
  nombre?: T;
  descripcion?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventos_select".
 */
export interface EventosSelect<T extends boolean = true> {
  estacion?: T;
  titulo?: T;
  tipo?: T;
  inicio?: T;
  fin?: T;
  descripcion?: T;
  lugar?: T;
  ciudad?: T;
  accion?: T;
  enlace?: T;
  portada?: T;
  slug?: T;
  estado?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transmisiones_select".
 */
export interface TransmisionesSelect<T extends boolean = true> {
  estacion?: T;
  titulo?: T;
  descripcion?: T;
  videoEnVivo?:
    | T
    | {
        activo?: T;
        fuente?: T;
        url?: T;
        numeroEvento?: T;
      };
  fecha?: T;
  especial?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publicidad_select".
 */
export interface PublicidadSelect<T extends boolean = true> {
  estacion?: T;
  titulo?: T;
  anunciante?: T;
  tipo?: T;
  inicio?: T;
  fin?: T;
  imagen?: T;
  imagenMovil?: T;
  enlace?: T;
  orden?: T;
  estado?: T;
  impresiones?: T;
  clics?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promociones_select".
 */
export interface PromocionesSelect<T extends boolean = true> {
  estacion?: T;
  titulo?: T;
  premio?: T;
  inicio?: T;
  fin?: T;
  descripcion?: T;
  participacion?: T;
  formulario?: T;
  urlExterna?: T;
  instrucciones?: T;
  ganadores?: T;
  portada?: T;
  slug?: T;
  estado?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "autores_select".
 */
export interface AutoresSelect<T extends boolean = true> {
  estacion?: T;
  nombre?: T;
  slug?: T;
  tipos?: T;
  cargo?: T;
  bio?: T;
  foto?: T;
  emailPublico?: T;
  x?: T;
  instagram?: T;
  wpId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bitacora_select".
 */
export interface BitacoraSelect<T extends boolean = true> {
  estacion?: T;
  sonoEn?: T;
  titulo?: T;
  artista?: T;
  cancion?: T;
  selector?: T;
  categoriaPlayout?: T;
  duracion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "canciones_select".
 */
export interface CancionesSelect<T extends boolean = true> {
  estacion?: T;
  titulo?: T;
  artista?: T;
  duracion?: T;
  portada?: T;
  embedUrl?: T;
  audio?: T;
  spotify?: T;
  appleMusic?: T;
  youtube?: T;
  deezer?: T;
  origen?: T;
  selector?: T;
  categoriaPlayout?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estado-muestras_select".
 */
export interface EstadoMuestrasSelect<T extends boolean = true> {
  momento?: T;
  niveles?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avisos_select".
 */
export interface AvisosSelect<T extends boolean = true> {
  titulo?: T;
  severidad?: T;
  estado?: T;
  mensaje?: T;
  componentes?: T;
  estaciones?: T;
  inicio?: T;
  resueltoEn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas_select".
 */
export interface PaginasSelect<T extends boolean = true> {
  estacion?: T;
  titulo?: T;
  contenido?: T;
  slug?: T;
  estado?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estaciones_select".
 */
export interface EstacionesSelect<T extends boolean = true> {
  nombre?: T;
  codigo?: T;
  nombrePublicacion?: T;
  dominio?: T;
  color?: T;
  logo?: T;
  logoReversa?: T;
  tritonMount?: T;
  notaStream?: T;
  preroll?: T;
  categoriasMusicales?:
    | T
    | {
        categoria?: T;
        id?: T;
      };
  facebook?: T;
  instagram?: T;
  x?: T;
  youtube?: T;
  tiktok?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auditoria_select".
 */
export interface AuditoriaSelect<T extends boolean = true> {
  coleccion?: T;
  documentoId?: T;
  documentoTitulo?: T;
  accion?: T;
  origen?: T;
  usuario?: T;
  usuarioCorreo?: T;
  usuarioRol?: T;
  estacion?: T;
  campos?: T;
  cambios?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  estacion?: T;
  categorias?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  submissionUploads?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskAplicarProgramacion".
 */
export interface TaskAplicarProgramacion {
  input: {
    collectionSlug: string;
    docId: number;
    accion: 'publicar' | 'despublicar' | 'desfijar';
    programadoPara: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskLimpiarBitacora".
 */
export interface TaskLimpiarBitacora {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | 'users'
      | 'media'
      | 'noticias'
      | 'programas'
      | 'podcasts'
      | 'categorias'
      | 'etiquetas'
      | 'especiales'
      | 'listas'
      | 'tipos-de-lista'
      | 'eventos'
      | 'transmisiones'
      | 'publicidad'
      | 'promociones'
      | 'autores'
      | 'bitacora'
      | 'canciones'
      | 'estado-muestras'
      | 'avisos'
      | 'paginas'
      | 'estaciones'
      | 'auditoria'
      | 'search'
      | 'redirects'
      | 'exports'
      | 'imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}
